# Generated by Django 5.2.7 on 2026-05-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0005_delete_maplayer'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificaterecord',
            name='certificate_type',
            field=models.CharField(choices=[('STANDARD', 'Standard Certificate'), ('SPECIAL', 'Special Certification (Restriction)')], default='STANDARD', max_length=20, verbose_name='Certificate Type'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='incident_record',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Incident Record'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='intended_purpose',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Intended Purpose'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='is_suitable',
            field=models.BooleanField(default=True, verbose_name='Is Suitable'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='purok_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Purok Name'),
        ),
    ]
