"""
Django settings for silay_drrmo project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import logging.config
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file (after BASE_DIR is defined)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# ============================================
# SECURITY SETTINGS
# ============================================
# SECURITY WARNING: keep the secret key used in production secret!
# In production, use environment variables instead of hardcoding
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-ray+$42+3p@)$4w00ul5-eftyn6%5eu$57*(y)peu=1p3!3tim')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Allowed hosts — auto-configured based on DEBUG mode
# DEBUG=True: Accept localhost and any ngrok tunnel (wildcards)
# DEBUG=False: Use single fixed production domain from .env
if DEBUG:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '.ngrok-free.app', '.ngrok-free.dev']
else:
    _prod_domain = os.getenv('PRODUCTION_DOMAIN')
    if not _prod_domain:
        raise ValueError("PRODUCTION_DOMAIN must be set in .env when DEBUG=False")
    ALLOWED_HOSTS = [_prod_domain]

# CSRF trusted origins — auto-generated from ALLOWED_HOSTS
# For each host, generate both http:// and https:// URLs (except localhost uses http only)
CSRF_TRUSTED_ORIGINS = []
for host in ALLOWED_HOSTS:
    if host in ('localhost', '127.0.0.1'):
        CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
    else:
        CSRF_TRUSTED_ORIGINS.append(f'http://{host}')
        CSRF_TRUSTED_ORIGINS.append(f'https://{host}')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    'users',
    'maps',
    'monitoring',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise serves compressed, cached static files directly via Gunicorn (no Nginx needed for /static/).
    # Must be placed immediately after SecurityMiddleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'silay_drrmo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'silay_drrmo.wsgi.application'


DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': os.getenv('DB_NAME', 'silaydrrmo_db'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}

# Validate required environment variables
if not os.getenv('DB_PASSWORD'):
    raise Exception('DB_PASSWORD environment variable is required. Please set it in your .env file.')


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# ============================================
# STATIC FILES CONFIGURATION
# ============================================
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'silay_drrmo/static')]

# WhiteNoise: serve gzip/brotli-compressed static files in production.
# CompressedStaticFilesStorage compresses files at collectstatic time so
# Gunicorn/Nginx serves them with Content-Encoding: gzip without overhead.
# (CompressedManifestStaticFilesStorage adds content-hash filenames too but
# crashes when a CSS file references a font that isn't present on disk.)
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files (user uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Create logs directory if it doesn't exist
LOGS_DIR = os.path.join(BASE_DIR, 'logs')
if not os.path.exists(LOGS_DIR):
    os.makedirs(LOGS_DIR)

# ============================================
# LOGGING CONFIGURATION - Enhanced
# ============================================
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
        'simple': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
    },
    'handlers': {
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
            'filters': ['require_debug_true'],
        },
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'monitoring.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'error_file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'errors.log'),
            'maxBytes': 1024 * 1024 * 10,  # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'api_file': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'api.log'),
            'maxBytes': 1024 * 1024 * 5,  # 5MB
            'backupCount': 3,
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'monitoring': {
            'handlers': ['console', 'file', 'error_file', 'api_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'maps': {
            'handlers': ['console', 'file', 'error_file'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
}

# Configure logging
logging.config.dictConfig(LOGGING)


# ============================================
# CACHING CONFIGURATION - Optional but Recommended
# ============================================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'monitoring-cache',
        'TIMEOUT': 300,  # 5 minutes default cache timeout
        'OPTIONS': {
            'MAX_ENTRIES': 1000
        }
    }
}


# ============================================
# WEATHER & FLOOD MONITORING CONFIGURATION
# ============================================

# ============================================
# API KEYS AND EXTERNAL SERVICES
# ============================================
# IMPORTANT: Store sensitive API keys in environment variables

# Silay City Coordinates (for weather API)
SILAY_LATITUDE = 10.753794
SILAY_LONGITUDE = 123.084160

# Cebu City Coordinates (for tide data)
CEBU_LATITUDE = 10.3167200
CEBU_LONGITUDE = 123.8907100

# API Keys - Use environment variables for security
WORLDTIDES_API_KEY = os.getenv('WORLDTIDES_API_KEY')  # Required from environment - no fallback

if not WORLDTIDES_API_KEY:
    raise Exception('WORLDTIDES_API_KEY environment variable is required. Please set it in your .env file.')

# Note: Open-Meteo API is free and doesn't require an API key
OPENMETEO_API_URL = 'https://api.open-meteo.com/v1/forecast'

# API Timeouts (in seconds)
WEATHER_API_TIMEOUT = 10
TIDE_API_TIMEOUT = 10

# Data update intervals
DATA_UPDATE_INTERVAL = 3 * 60 * 60  # 3 hours in seconds
DATA_RETENTION_DAYS = 365  # Keep 1 year of historical data


# ============================================
# FLOOD PREDICTION CONFIGURATION
# ============================================

# Risk calculation thresholds (can be overridden in database RiskThreshold model)
RISK_THRESHOLDS = {
    'rainfall': {
        'low': 30,        # mm
        'moderate': 50,   # mm
        'high': 100,      # mm
    },
    'tide': {
        'low': 1.0,       # meters
        'moderate': 1.5,  # meters
        'high': 2.0,      # meters
    },
    'rainfall_intensity': {
        'heavy': 15,      # mm per day
        'very_heavy': 25, # mm per day
        'extreme': 50,    # mm per day
    }
}

# Flood-prone barangays (customize based on your city)
FLOOD_PRONE_BARANGAYS = [
    'Barangay 1',
    'Barangay 5', 
    'Barangay 7',
    # Add more as needed
]

# Seasonal rainfall expectations (millimeters)
SEASONAL_RAINFALL = {
    1: 30,    # January - Dry
    2: 25,    # February - Dry
    3: 35,    # March - Dry
    4: 50,    # April - Pre-Monsoon
    5: 150,   # May - Monsoon Start
    6: 200,   # June - Monsoon
    7: 200,   # July - Monsoon
    8: 200,   # August - Monsoon
    9: 250,   # September - Peak Monsoon
    10: 180,  # October - Monsoon End
    11: 100,  # November - Post-Monsoon
    12: 50,   # December - Dry Season Start
}

# Recommendation priorities
RECOMMENDATION_PRIORITIES = {
    'high': {'color': 'red', 'action_required': True},
    'medium': {'color': 'yellow', 'action_required': False},
    'low': {'color': 'green', 'action_required': False},
}


# ============================================
# ALERTS & NOTIFICATIONS CONFIGURATION
# ============================================

# Alert settings
ALERT_SETTINGS = {
    'critical_alert_threshold': 3.5,  # Risk level >= 3.5 triggers critical alert
    'high_alert_threshold': 2.5,      # Risk level >= 2.5 triggers high alert
    'enable_email_alerts': False,      # Set to True to enable email notifications
    'enable_sms_alerts': False,        # Set to True to enable SMS notifications
    'alert_recipients': [
        'drrmo@silay.gov.ph',
    ],
    'sms_recipients': [
        # Add emergency contact numbers here
    ]
}


# ============================================
# EMAIL CONFIGURATION (for alerts)
# ============================================

EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  # Console for development
# For production, use:
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@gmail.com'
# EMAIL_HOST_PASSWORD = 'your-app-password'
# DEFAULT_FROM_EMAIL = 'your-email@gmail.com'


# ============================================
# ADMIN REGISTRATION SECURITY
# ============================================
# Admin Registration Key - MUST be set in environment variables!
# Use a strong, random key for production
ADMIN_REGISTRATION_KEY = os.getenv('ADMIN_REGISTRATION_KEY')

if not ADMIN_REGISTRATION_KEY:
    raise Exception('ADMIN_REGISTRATION_KEY environment variable is required. Please set it in your .env file.')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================
# GIS LIBRARY PATHS
# ============================================
# Detect platform and set GDAL/GEOS library paths
# These are required for GeoDjango to work with spatial data

if os.name != "nt":  # Unix/Linux systems (not Windows)
    # Paths remain configurable via env vars for flexibility across local setups.
    # Defaults match Ubuntu 22.04/24.04 and Debian Bookworm x86_64.
    os.environ["GDAL_LIBRARY_PATH"] = os.getenv(
        "GDAL_LIBRARY_PATH", "/usr/lib/x86_64-linux-gnu/libgdal.so"
    )
    os.environ["GEOS_LIBRARY_PATH"] = os.getenv(
        "GEOS_LIBRARY_PATH", "/usr/lib/x86_64-linux-gnu/libgeos_c.so"
    )
else:  # Windows systems
    # Uncomment and set these paths if you're using OSGeo4W on Windows
    # GDAL_LIBRARY_PATH = r"C:\OSGeo4W\bin\gdal310.dll"
    # GEOS_LIBRARY_PATH = r"C:\OSGeo4W\bin\geos_c.dll"
    pass

# ============================================
# AUTHENTICATION SETTINGS
# ============================================
# Custom user model for extended authentication
AUTH_USER_MODEL = 'users.CustomUser'

# Login URL - redirect to login page if not authenticated
LOGIN_URL = '/'


# ============================================
# SECURITY SETTINGS FOR PRODUCTION
# ============================================

if not DEBUG:
    # NEVER set SECURE_SSL_REDIRECT here — Nginx (the reverse proxy) is responsible
    # for HTTP→HTTPS redirects. If Django also redirects, it creates redirect loops.
    SECURE_SSL_REDIRECT = False

    # Tell Django it's sitting behind Nginx which terminates SSL.
    # Nginx sets X-Forwarded-Proto: https, so Django knows the original request was HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # HTTPS_ENABLED=True in .env activates cookie security and HSTS.
    # Keep False until SSL certificates are installed in Nginx.
    _https_enabled = os.getenv('HTTPS_ENABLED', 'False') == 'True'

    SESSION_COOKIE_SECURE = _https_enabled
    CSRF_COOKIE_SECURE = _https_enabled
    CSRF_COOKIE_HTTPONLY = _https_enabled

    # HSTS — only activate after SSL is confirmed working, otherwise it bricks HTTP access
    SECURE_HSTS_SECONDS = 31536000 if _https_enabled else 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = _https_enabled
    SECURE_HSTS_PRELOAD = _https_enabled

    SECURE_BROWSER_XSS_FILTER = True
    X_FRAME_OPTIONS = 'DENY'
else:
    # DEVELOPMENT settings - Allow HTTP and easier debugging
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_HTTPONLY = False


# ============================================
# SESSION & COOKIE CONFIGURATION
# ============================================

SESSION_COOKIE_AGE = 86400  # 24 hours
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_COOKIE_HTTPONLY = True